# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eLocalShoppieSvc
  labels:
    app: eLocalShoppieSvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eLocalShoppieSvc
  template:
    metadata:
      labels:
        app: eLocalShoppieSvc
    spec:
      containers:
      - name: eLocalShoppieSvc
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true


